--- #YAML:1.0
name:               Socket-MsgHdr
version:            0.03
abstract:           sendmsg, recvmsg and ancillary data operations
author:
    - A. U. Thor <mjp@domain_not_set.invalid>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
